### ISSUE TITLE
Crashes when two clients connect

### ISSUE THREAD

**Issue by pyro2927** [pyro2927/Hallucinate#1]
```go
panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

goroutine 69 [running]:
io/ioutil.readAll.func1(0xc42050de58)
        /usr/lib/go-1.10/src/io/ioutil/ioutil.go:30 +0x104
panic(0x6c1540, 0x8ac4a0)
        /usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
bufio.(*Reader).Read(0xc420020960, 0xc420568ffc, 0x18f, 0xe04, 0x1fc, 0x0, 0x0)
        /usr/lib/go-1.10/src/bufio/bufio.go:227 +0x3bf
github.com/gorilla/websocket.(*messageReader).Read(0xc4205402a8, 0xc420568ffc, 0xe04, 0xe04, 0x1fc, 0x0, 0x0)
        /home/joe/src/github.com/gorilla/websocket/conn.go:985 +0x233
bytes.(*Buffer).ReadFrom(0xc420368cb0, 0x7f397e314000, 0xc4205402a8, 0x6c28c0, 0x0, 0x7f397e314000)
        /usr/lib/go-1.10/src/bytes/buffer.go:205 +0xa0
io/ioutil.readAll(0x7f397e314000, 0xc4205402a8, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/io/ioutil/ioutil.go:36 +0xb5
io/ioutil.ReadAll(0x7f397e314000, 0xc4205402a8, 0x7f397e314000, 0xc4205402a8, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/io/ioutil/ioutil.go:45 +0x3e
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc420013340, 0xc4202dbb80, 0x1d, 0x20, 0x0, 0x20, 0x0)
        /home/joe/src/github.com/gorilla/websocket/conn.go:1030 +0x8d
github.com/pyro2927/hallucinate/fates_call.(*League).StartListening(0xc420094a50, 0xc4203fa100)
        /home/joe/src/github.com/pyro2927/hallucinate/fates_call/fates_call.go:68 +0x44
created by main.handleMessage
        /home/joe/src/github.com/pyro2927/hallucinate/rift_walk/rift.go:175 +0x778
exit status 2
```

**Comment by pyro2927** [comment]
Probably due to two goroutines trying to pull messages off the websocket connections
